#!/bin/bash

USER_ID=gerard
HOST_UID=$USER

source ../ipList

CNODE=$USRP10
ENODE0=$USRP10
ENODE1=$USRP9
ENODE2=$USRP4
ENODE3=$USRP3

cd ..
genMatInst 10 9 4 3
cp matInst /home/$HOST_UID/wdemo/dev/umat/tools/cli
rm -f ../matInst
cd users

./pInstall -i $USER_ID -t cnode -c $CNODE
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE0
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE1
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE2
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE3
./pInstall -i $USER_ID -t usr   -u $CNODE

