#!/bin/bash

USER_ID=han
HOST_UID=$USER

source ../ipList

CNODE=$USRP6
ENODE0=$USRP6
ENODE1=$USRP1
ENODE2=$USRP5
ENODE3=$USRP7
ENODE4=$USRP8

cd ..
genMatInst 6 1 5 7 8
cp matInst /home/$HOST_UID/wdemo/dev/umat/tools/cli
rm -f matInst
cd users

./pInstall -i $USER_ID -t cnode -c $CNODE
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE0
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE1
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE2
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE3
./pInstall -i $USER_ID -t enode -c $CNODE -e $ENODE4
./pInstall -i $USER_ID -t usr   -u $CNODE
